name: Integration Tests

on: push

jobs:
  go-tests:
    name: Run Terratest Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: autero1/action-terraform@v1.0.0
        with:
          terraform_version: 0.14.8

      - name: Run Go Tests
        run: make test
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CI_CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_EMAIL: ${{ secrets.CI_CLOUDFLARE_EMAIL }}
